# Generated by Django 2.2.1 on 2019-06-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190617_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='batsman',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='batting_team',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='bowler',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='bowling_team',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='dismissal_kind',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='fielder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='non_stricker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='player_dismissed',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
