# Generated by Django 2.2.1 on 2019-06-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='acronym',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
